### ISSUE TITLE
CodeSytle checking / Styleguide

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#2]
Ausarbeiten eines Styleguides zB. JS hint.

**Comment by janlelis** [comment]
JSHint sieht hilfreich aus.

In der `develop` branch gibt es jetzt eine `.jshintrc`, in welche wie ein paar style-konfigurationen setzen können.

Hier eine Liste der verfügbaren Integrationen von jshint in verschiedenen Editoren: http://jshint.com/install/

Manche davon benötigen, dass man per Hand das jshint-Kommandlinetool installiert:

    $ sudo npm install -g jshint
