### ISSUE TITLE
Filter erstellen

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#23]
Es müssen die Filter noch implementiert werden, die dann über das JSON weitergegeben werden. Mögliche Filter sind:
- Geschlecht
- Herkunftsland
- relative Häufigkeit

Die Filter der Quellen und des Chromosoms, wurden bereits implementiert.

**Comment by BenSchumacher-HU** [comment]
Ist das fertig?

**Comment by kasperkopf** [comment]
done
