### ISSUE TITLE
Intervall in Ideogramm auswählen

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#26]
Es muss eine Logik erstellt werden die das Positionieren mithilfe des Mauszeigers im Ideogramm ermöglicht.
- Gesamtanzahl der Basenpaare pro Chromosom zur Chromosomliste hinzufügen (in `src/js/backend/embedded_data.js`)
- Ziel ist: das Klicks auf eine Position in der GUI-Componente eine Funktion aufrufen, welche die genaue geklickte Position beinhalten, bzw. die aktuelle Position auf die Gesamtzahl der Basenpaare darstellen
- eine Methode um die Position als Klick auf einem Bild zubekommen bei StackOverflow: http://stackoverflow.com/questions/2159044/getting-the-x-y-coordinates-of-a-mouse-click-on-an-image-with-jquery

**Comment by BenSchumacher-HU** [comment]
Ist das als Feature gestrichen?

**Comment by kasperkopf** [comment]
jo nicht genug zeit für gehabt wird gestrichen
