### ISSUE TITLE
Testsuit für React-Componenten aufsetzten

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#27]

**Comment by kasperkopf** [comment]
done, aber mit travis gibt es noch einen bug

**Comment by BenSchumacher-HU** [comment]
Was ist das für ein Bug?

**Comment by janlelis** [comment]
@BenSchumacher-HU Travis kann unsere test suite nicht ausführen, weil er ein pre-compile plugin nicht aktiviert: https://travis-ci.org/hu-semesterprojekt-genombrowser/Alazen-GUI/jobs/104947884
