### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#3]
Bitte alle kommentieren, ob sie den Setup hinbekommen haben oder noch Probleme haben, damit alle auf dem gleichen Stand der Dinge sind.

**Comment by kasperkopf** [comment]
Setup hat gut funktioniert unter Arch Linux, Testseite funktioniert bei mir, bin also fertig.

**Comment by ismirlatte** [comment]
Läuft!

**Comment by AleksandarAtanasov91** [comment]
Wenn ich nur die Seite mit der React-Komponente sehen und den Server starten können soll, dann bin ich auch fertig :-) (Unter Ubuntu 14.04 64-bit)

**Comment by huinfostudent** [comment]
Hi,
bei mir hat es leider nicht geklappt, weder unter Ubuntu noch unter Windows :-(.
Ich bringe morgen meinen Laptop mit.
