### ISSUE TITLE
JSON anpassen

### ISSUE THREAD

**Issue by kasperkopf** [hu-semesterprojekt-genombrowser/Alazen-GUI#5]
JSON müssen angepasst werden und Rücksprache mit Middleware Team.
* für jede Quelle eine JSON Anfrage mit eigener Rückgabe
* bei schlechter Performance (zu viel Informationen im JSON), muss Middleware weniger im JSON mitgeben

**Comment by kasperkopf** [comment]
Ändern: Pro Lane eine JSON Anfrage

**Comment by BenSchumacher-HU** [comment]
Ist das noch aktuell?

**Comment by kasperkopf** [comment]
nein -> closed
